-- ═══════════════════════════════════════════════════════════════════════
-- Rizvi Family Tree — seed data
--
-- GENERATED FILE. Do not edit by hand: change assets/data.js and re-run
--   node tools/gen-seed-sql.js
--
-- Run after schema.sql. SAFE TO RE-RUN: a value the family has already
-- entered or corrected is never overwritten. Only fields that are currently
-- empty get filled in, so re-running after new fields are added (such as the
-- Urdu columns) backfills them without undoing anyone's work.
-- ═══════════════════════════════════════════════════════════════════════

insert into public.people (id, parent, name, name_ur, birth, birth_ur, death, death_ur, birthplace, birthplace_ur, residence, residence_ur, spouse, spouse_ur, notes, notes_ur, tag, locked, sort_order) values
  ('ali-hussain-rizvi', null, 'Mir Ali Hussain Rizvi', 'میر علی حسین رضوی', 'c. 1792–1793 (estimated)', 'تقریباً ۱۷۹۲–۱۷۹۳ء (تخمینی)', '', '', '', '', 'Lucknow', 'لکھنؤ', '', '', 'Earliest confirmed ancestor. Birth year estimated using a 30-year average generation gap back from Syed Hussain Ali Rizvi (b. 1882–1883) across three generations. The shajra dated the equivalent entry to c. 1650 AD, but the family understands that to have been a rough guess rather than a documented date, so the later estimate is treated as the better working figure.', 'سب سے قدیم مصدقہ جدِ امجد۔ سالِ پیدائش کا تخمینہ سید حسین علی رضوی (پیدائش ۱۸۸۲–۱۸۸۳ء) سے تین پشتیں پیچھے، فی پشت تیس سال کے اوسط کے حساب سے لگایا گیا ہے۔ شجرے میں اسی اندراج کی تاریخ تقریباً ۱۶۵۰ء درج ہے، مگر خاندان کے مطابق وہ محض ایک اندازہ تھا، کوئی دستاویزی تاریخ نہیں؛ اسی لیے بعد والے تخمینے کو بہتر عملی تاریخ سمجھا جاتا ہے۔', 'estimated', '{}', 0),
  ('ghulam-raza-rizvi-sr', 'ali-hussain-rizvi', 'Mir Ghulam Raza Rizvi', 'میر غلام رضا رضوی', '', '', '', '', '', '', 'Lucknow', 'لکھنؤ', '', '', 'Son of Mir Ali Hussain Rizvi. The family has confirmed the shajra''s generation order — Mir Ghulam Raza Rizvi comes before Syed Afzal Hussain Rizvi. An earlier family recollection had these two reversed.', 'میر علی حسین رضوی کے فرزند۔ خاندان نے شجرے میں دی گئی پشتوں کی ترتیب کی تصدیق کر دی ہے — میر غلام رضا رضوی، سید افضل حسین رضوی سے پہلے آتے ہیں۔ خاندان کی پہلی یاد میں یہ دونوں الٹ تھے۔', 'confirmed', '{}', 1),
  ('afzal-hussain-rizvi', 'ghulam-raza-rizvi-sr', 'Syed Afzal Hussain Rizvi', 'سید افضل حسین رضوی', '', '', '', '', '', '', 'Lucknow', 'لکھنؤ', 'Syeda Fatima Begum', 'سیدہ فاطمہ بیگم', 'Of Lucknow. Buried in Lucknow, consistent with the family''s residence in Mohalla Nakkhas. The Talkatora Karbala in that quarter is a plausible burial site but has not been confirmed.', 'لکھنؤ کے رہنے والے۔ لکھنؤ ہی میں مدفون ہیں، جو محلہ نکھاس میں خاندان کی رہائش سے مطابقت رکھتا ہے۔ اسی محلے کی تل کٹورہ کربلا ایک ممکنہ مدفن ہو سکتی ہے، مگر اس کی تصدیق نہیں ہوئی۔', 'confirmed', '{}', 2),
  ('hussain-ali-rizvi', 'afzal-hussain-rizvi', 'Syed Hussain Ali Rizvi', 'سید حسین علی رضوی', 'b. 1882–1883 (estimated)', 'پیدائش ۱۸۸۲–۱۸۸۳ء (تخمینی)', 'd. c. 1950', 'وفات تقریباً ۱۹۵۰ء', 'Lucknow', 'لکھنؤ', 'Lucknow, later Murshidabad', 'لکھنؤ، بعد ازاں مرشد آباد', 'Nowrozi Begum (3rd wife), b. 1912–1913 (estimated)', 'نوروزی بیگم (تیسری اہلیہ)، پیدائش ۱۹۱۲–۱۹۱۳ء (تخمینی)', 'A religious scholar and zakir. Birth year estimated from the family recollection that he was 45 at his marriage to Nowrozi Begum around 1927–1928; she was 15, giving her birth as 1912–1913. Separate family recollection puts him at approximately 1870–1880; the shajra says 1870.

He had three wives. His first wife, mother of Syed Ali Rizvi, passed away shortly after childbirth. He then married her sister, who also passed away shortly after her own childbirth — likely the mother of Yousuf Jahan, given her position in the birth order. Nowrozi Begum, the third wife and daughter of Sheikh Munawwar Ali, was the mother of the remaining children.

Moved from Lucknow to Murshidabad; the family recalls this was because his sister married into a Nawab family there whose title ended in "Jah". Owned property in Ikraam Ganj, Murshidabad, and refurbished a mosque there (name not yet recorded). Buried at a site the family calls Hussaini Dalan in Murshidabad. After he passed away around 1950 the family relocated to Dhaka around 1951.', 'عالمِ دین اور ذاکر۔ سالِ پیدائش کا تخمینہ خاندان کی اس یاد سے لگایا گیا ہے کہ نوروزی بیگم سے نکاح کے وقت، تقریباً ۱۹۲۷–۱۹۲۸ء میں، ان کی عمر ۴۵ برس تھی؛ نوروزی بیگم کی عمر ۱۵ برس تھی، جس سے ان کی پیدائش ۱۹۱۲–۱۹۱۳ء بنتی ہے۔ خاندان کی ایک الگ یاد کے مطابق ان کی پیدائش تقریباً ۱۸۷۰–۱۸۸۰ء کے درمیان ہے؛ شجرے میں ۱۸۷۰ء درج ہے۔

ان کی تین بیویاں تھیں۔ پہلی اہلیہ، جو سید علی رضوی کی والدہ تھیں، ولادت کے کچھ ہی عرصے بعد انتقال کر گئیں۔ اس کے بعد انہوں نے ان کی ہمشیرہ سے نکاح کیا (دوسری اہلیہ)، جو خود بھی اپنی ولادت کے کچھ عرصے بعد انتقال کر گئیں — ترتیبِ ولادت کے اعتبار سے غالباً وہی یوسف جہاں کی والدہ تھیں۔ تیسری اہلیہ نوروزی بیگم، جو شیخ منور علی کی صاحبزادی تھیں، باقی تمام اولاد کی والدہ تھیں۔

لکھنؤ سے مرشد آباد منتقل ہوئے؛ خاندان کو یاد ہے کہ اس کی وجہ یہ تھی کہ ان کی ہمشیرہ کی شادی وہاں کے ایک نوابی خاندان میں ہوئی تھی جس کے لقب کا اختتام "جاہ" پر ہوتا تھا۔ مرشد آباد میں اکرام گنج میں جائیداد کے مالک تھے اور وہاں ایک مسجد کی تجدید کرائی (نام ابھی درج نہیں)۔ مرشد آباد میں اس مقام پر مدفون ہیں جسے خاندان "حسینی دالان" کہتا ہے۔ تقریباً ۱۹۵۰ء میں ان کی وفات کے بعد خاندان تقریباً ۱۹۵۱ء میں ڈھاکہ منتقل ہو گیا۔', 'estimated', '{}', 3),
  ('syed-ali-rizvi', 'hussain-ali-rizvi', 'Syed Ali Rizvi', 'سید علی رضوی', 'b. 1925', 'پیدائش ۱۹۲۵ء', '', '', '', '', 'Karachi', 'کراچی', '', '', 'First son. His mother was Syed Hussain Ali Rizvi''s first wife, who passed away shortly after his birth. The shajra''s independently recorded 1925 lines up well with the age-gap estimate of c. 1922–1925.', 'پہلے فرزند۔ ان کی والدہ سید حسین علی رضوی کی پہلی اہلیہ تھیں، جو ان کی ولادت کے کچھ ہی عرصے بعد انتقال کر گئیں۔ شجرے میں الگ سے درج ۱۹۲۵ء عمر کے فرق سے لگائے گئے تخمینے (تقریباً ۱۹۲۲–۱۹۲۵ء) سے خوب مطابقت رکھتا ہے۔', 'confirmed', '{}', 4),
  ('yousuf-jahan', 'hussain-ali-rizvi', 'Yousuf Jahan', 'یوسف جہاں', 'b. c. 1924–1927 (estimated)', 'پیدائش تقریباً ۱۹۲۴–۱۹۲۷ء (تخمینی)', '', '', '', '', 'Karachi', 'کراچی', '', '', 'Elder step-sister to Hussain Raza''s father. Her mother was likely Syed Hussain Ali Rizvi''s second wife (sister of the first), who also passed away shortly after childbirth. Birth year estimated from being recalled as 3–5 years older than Wasi Ali.', 'حسین رضا کے والد کی بڑی سوتیلی ہمشیرہ۔ غالباً ان کی والدہ سید حسین علی رضوی کی دوسری اہلیہ تھیں (پہلی اہلیہ کی ہمشیرہ)، جو خود بھی ولادت کے کچھ عرصے بعد انتقال کر گئیں۔ سالِ پیدائش کا تخمینہ اس یاد سے لگایا گیا کہ وہ وصی علی سے تین تا پانچ برس بڑی تھیں۔', 'estimated', '{}', 5),
  ('wasi-ali', 'hussain-ali-rizvi', 'Wasi Ali', 'وصی علی', 'b. c. 1929–1930 (estimated)', 'پیدائش تقریباً ۱۹۲۹–۱۹۳۰ء (تخمینی)', 'd. 2013, aged approximately 85', 'وفات ۲۰۱۳ء، تقریباً ۸۵ برس کی عمر میں', '', '', 'Karachi', 'کراچی', 'Hilal Begum', 'ہلال بیگم', 'Eldest son of Nowrozi Begum, born the year after her marriage. Remains shajra-only and has not yet been independently confirmed. Died December 2013 aged approximately 85.', 'نوروزی بیگم کے سب سے بڑے فرزند، ان کی شادی کے اگلے برس پیدا ہوئے۔ ابھی تک صرف شجرے میں درج ہیں اور آزادانہ تصدیق باقی ہے۔ دسمبر ۲۰۱۳ء میں تقریباً ۸۵ برس کی عمر میں انتقال ہوا۔', 'shajra', '{}', 6),
  ('wazir-ali', 'hussain-ali-rizvi', 'Wazir Ali', 'وزیر علی', 'b. c. 1932–1933 (estimated)', 'پیدائش تقریباً ۱۹۳۲–۱۹۳۳ء (تخمینی)', 'd. 2005', 'وفات ۲۰۰۵ء', '', '', 'Lahore', 'لاہور', 'Sughra Begum', 'صغریٰ بیگم', 'Remains shajra-only and has not yet been independently confirmed. Birth year estimated from the recollection that Wasi Ali, Wazir Ali and Jafar Hussain were each born at most 2 years apart.', 'ابھی تک صرف شجرے میں درج ہیں اور آزادانہ تصدیق باقی ہے۔ سالِ پیدائش کا تخمینہ اس یاد سے لگایا گیا کہ وصی علی، وزیر علی اور جعفر حسین میں سے ہر ایک کے درمیان زیادہ سے زیادہ دو برس کا فرق تھا۔', 'shajra', '{}', 7),
  ('jafar-hussain', 'hussain-ali-rizvi', 'Jafar Hussain', 'جعفر حسین', 'b. 1934', 'پیدائش ۱۹۳۴ء', 'd. 2006', 'وفات ۲۰۰۶ء', '', '', 'Rawalpindi', 'راولپنڈی', 'Sarwari Begum', 'سروری بیگم', 'Per shajra. His 1934 birth is the anchor from which Wasi Ali''s and Wazir Ali''s birth years were estimated.', 'بمطابق شجرہ۔ ان کا سنِ پیدائش ۱۹۳۴ء وہ بنیاد ہے جس سے وصی علی اور وزیر علی کے سنینِ پیدائش کا تخمینہ لگایا گیا۔', 'shajra', '{}', 8),
  ('muhammad-ali-yousuf', 'jafar-hussain', 'Muhammad Ali', 'محمد علی', '', '', '', '', '', '', '', '', '', '', 'Known as Yousuf.', 'یوسف کے نام سے معروف۔', 'confirmed', '{}', 9),
  ('batool', 'jafar-hussain', 'Batool', 'بتول', '', '', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 10),
  ('phool', 'jafar-hussain', 'Phool', 'پھول', '', '', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 11),
  ('shazia', 'jafar-hussain', 'Shazia', 'شازیہ', '', '', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 12),
  ('mustafa', 'jafar-hussain', 'Mustafa', 'مصطفیٰ', '', '', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 13),
  ('fatima-begum', 'hussain-ali-rizvi', 'Fatima Begum', 'فاطمہ بیگم', '', '', '', '', '', '', 'Murshidabad', 'مرشد آباد', '', '', 'Per shajra.', 'بمطابق شجرہ۔', 'shajra', '{}', 14),
  ('hakeema-begum', 'hussain-ali-rizvi', 'Hakeema Begum', 'حکیمہ بیگم', 'b. c. 1944–1945 (estimated)', 'پیدائش تقریباً ۱۹۴۴–۱۹۴۵ء (تخمینی)', '', '', '', '', '', '', 'Abul Hasan Rizvi', 'ابوالحسن رضوی', 'Birth year derived from being recalled as 5 years older than Syed Ghulam Raza Rizvi.', 'سالِ پیدائش اس یاد سے اخذ کیا گیا کہ وہ سید غلام رضا رضوی سے پانچ برس بڑی تھیں۔', 'estimated', '{}', 15),
  ('faiz-ul-hasan', 'hakeema-begum', 'Faiz ul Hasan', 'فیض الحسن', '', '', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 16),
  ('najmul-hasan', 'hakeema-begum', 'Najmul Hasan', 'نجم الحسن', '', '', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 17),
  ('afzal-hussain', 'hussain-ali-rizvi', 'Afzal Hussain', 'افضل حسین', 'b. c. 1946–1947 (estimated)', 'پیدائش تقریباً ۱۹۴۶–۱۹۴۷ء (تخمینی)', 'd. 2021', 'وفات ۲۰۲۱ء', '', '', 'Karachi', 'کراچی', 'Tahira', 'طاہرہ', 'Nine children: 5 sons and 4 daughters. Their names and birth years are not yet recorded — this is an open question on the research list, and one of the most useful gaps for the family to fill in. Birth year derived from being recalled as 3 years older than Syed Ghulam Raza Rizvi.', 'نو اولاد: پانچ بیٹے اور چار بیٹیاں۔ ان کے نام اور سنینِ پیدائش ابھی درج نہیں ہوئے — یہ تحقیق طلب سوالات میں شامل ہے اور خاندان کے لیے سب سے مفید خلا میں سے ایک ہے۔ سالِ پیدائش اس یاد سے اخذ کیا گیا کہ وہ سید غلام رضا رضوی سے تین برس بڑے تھے۔', 'estimated', '{}', 18),
  ('ghulam-raza-rizvi', 'hussain-ali-rizvi', 'Syed Ghulam Raza Rizvi', 'سید غلام رضا رضوی', 'b. c. 1949–1950', 'پیدائش تقریباً ۱۹۴۹–۱۹۵۰ء', 'd. 1 January 2015', 'وفات یکم جنوری ۲۰۱۵ء', 'Murshidabad', 'مرشد آباد', 'Dubai', 'دبئی', 'Tasneem Fatima, b. 1950 (Naqvi descent)', 'تسنیم فاطمہ، پیدائش ۱۹۵۰ء (نقوی نسب)', 'Elders recall he was a newborn, or not yet born, when Syed Hussain Ali Rizvi passed away around 1950. Confirmed as the "Ghulam Raza" shown in the shajra as a child of Syed Hussain Ali Rizvi. The shajra''s death year of 2013 is incorrect — he passed away on 1 January 2015 in Dubai. His wife''s full name is Tasneem Fatima, of Naqvi descent; the shajra''s "Tasneem Naqvi" was a shortened form.', 'بزرگوں کو یاد ہے کہ تقریباً ۱۹۵۰ء میں سید حسین علی رضوی کی وفات کے وقت یہ نومولود تھے یا ابھی پیدا نہیں ہوئے تھے۔ شجرے میں سید حسین علی رضوی کے فرزند کے طور پر درج "غلام رضا" کی بطور انہی کے تصدیق ہو چکی ہے۔ شجرے میں درج سالِ وفات ۲۰۱۳ء غلط ہے — ان کا انتقال یکم جنوری ۲۰۱۵ء کو دبئی میں ہوا۔ ان کی اہلیہ کا پورا نام تسنیم فاطمہ ہے، نقوی نسب سے؛ شجرے کا "تسنیم نقوی" مختصر صورت تھی۔', 'confirmed', '{}', 19),
  ('siper-fatima', 'ghulam-raza-rizvi', 'Syeda Siper Fatima Rizvi', 'سیدہ سپر فاطمہ رضوی', 'b. 1973', 'پیدائش ۱۹۷۳ء', '', '', '', '', '', '', 'Syed Hasan Imam Naqvi', 'سید حسن امام نقوی', 'Eldest of Syed Ghulam Raza Rizvi''s children.', 'سید غلام رضا رضوی کی سب سے بڑی اولاد۔', 'confirmed', '{}', 20),
  ('amal-hasan', 'siper-fatima', 'Amal Hasan', 'امل حسن', 'b. 1999', 'پیدائش ۱۹۹۹ء', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 21),
  ('manahil-hasan', 'siper-fatima', 'Manahil Hasan', 'مناہل حسن', 'b. 2004', 'پیدائش ۲۰۰۴ء', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 22),
  ('shaza-hasan', 'siper-fatima', 'Shaza Hasan', 'شازہ حسن', 'b. 2006', 'پیدائش ۲۰۰۶ء', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 23),
  ('abbas-raza', 'ghulam-raza-rizvi', 'Abbas Raza', 'عباس رضا', 'b. 1975', 'پیدائش ۱۹۷۵ء', '', '', '', '', '', '', 'Aatika Fatima', 'عاتکہ فاطمہ', 'Eldest brother.', 'سب سے بڑے بھائی۔', 'confirmed', '{}', 24),
  ('ali-raza-rizvi', 'abbas-raza', 'Syed Ali Raza Rizvi', 'سید علی رضا رضوی', 'b. 2001', 'پیدائش ۲۰۰۱ء', '', '', '', '', '', '', 'Masooma Rizvi', 'معصومہ رضوی', '', '', 'confirmed', '{}', 25),
  ('fatima-abbas-rizvi', 'abbas-raza', 'Syeda Fatima Abbas Rizvi', 'سیدہ فاطمہ عباس رضوی', 'b. 2002', 'پیدائش ۲۰۰۲ء', '', '', '', '', '', '', 'Meesum Naqvi', 'میثم نقوی', '', '', 'confirmed', '{}', 26),
  ('haider-raza-rizvi', 'abbas-raza', 'Syed Haider Raza Rizvi', 'سید حیدر رضا رضوی', 'b. 2011', 'پیدائش ۲۰۱۱ء', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 27),
  ('shabbar-raza', 'ghulam-raza-rizvi', 'Shabbar Raza', 'شبر رضا', 'b. 1976', 'پیدائش ۱۹۷۶ء', '', '', '', '', '', '', 'Tabassum Fatima', 'تبسم فاطمہ', '', '', 'confirmed', '{}', 28),
  ('rabab-fatima', 'ghulam-raza-rizvi', 'Syeda Rabab Fatima Rizvi', 'سیدہ رباب فاطمہ رضوی', 'b. 1982', 'پیدائش ۱۹۸۲ء', '', '', '', '', '', '', 'Shujat Hasan', 'شجاعت حسن', '', '', 'confirmed', '{}', 29),
  ('fasahat-hussain', 'rabab-fatima', 'Fasahat Hussain', 'فصاحت حسین', 'b. 2009', 'پیدائش ۲۰۰۹ء', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 30),
  ('hussain-raza', 'ghulam-raza-rizvi', 'Hussain Raza', 'حسین رضا', 'b. 1983', 'پیدائش ۱۹۸۳ء', '', '', '', '', '', '', 'Tania Hussain', 'تانیہ حسین', 'Youngest of Syed Ghulam Raza Rizvi''s children. Compiler of this family record.', 'سید غلام رضا رضوی کی سب سے چھوٹی اولاد۔ اس خاندانی ریکارڈ کے مرتب۔', 'confirmed', '{}', 31),
  ('muslim-raza-rizvi', 'hussain-raza', 'Muhammad Muslim Raza Rizvi', 'محمد مسلم رضا رضوی', 'b. 2014', 'پیدائش ۲۰۱۴ء', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 32),
  ('ali-yousuf-raza-rizvi', 'hussain-raza', 'Ali Yousuf Raza Rizvi', 'علی یوسف رضا رضوی', 'b. 2018', 'پیدائش ۲۰۱۸ء', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 33),
  ('younus-hasan-raza-rizvi', 'hussain-raza', 'Younus Hasan Raza Rizvi', 'یونس حسن رضا رضوی', 'b. 2019', 'پیدائش ۲۰۱۹ء', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 34),
  ('isa-hussain-raza-rizvi', 'hussain-raza', 'Isa Hussain Raza Rizvi', 'عیسیٰ حسین رضا رضوی', 'b. 2022', 'پیدائش ۲۰۲۲ء', '', '', '', '', '', '', '', '', '', '', 'confirmed', '{}', 35),
  ('sughra-begum-sister', 'afzal-hussain-rizvi', 'Syeda Sughra Begum', 'سیدہ صغریٰ بیگم', '', '', '', '', '', '', '', '', '', '', 'Sister of Syed Hussain Ali Rizvi. 2 sons and 3 daughters, names not recorded (per shajra).', 'سید حسین علی رضوی کی ہمشیرہ۔ دو بیٹے اور تین بیٹیاں، نام درج نہیں (بمطابق شجرہ)۔', 'shajra', '{}', 36),
  ('zehra-begum-sister', 'afzal-hussain-rizvi', 'Syeda Zehra Begum', 'سیدہ زہرا بیگم', '', '', '', '', '', '', '', '', '', '', 'Sister of Syed Hussain Ali Rizvi. 1 son, name not recorded (per shajra).', 'سید حسین علی رضوی کی ہمشیرہ۔ ایک بیٹا، نام درج نہیں (بمطابق شجرہ)۔', 'shajra', '{}', 37),
  ('ali-raza-brother', 'afzal-hussain-rizvi', 'Syed Ali Raza', 'سید علی رضا', '', '', '', '', '', '', '', '', '', '', 'Brother of Syed Hussain Ali Rizvi (per shajra).', 'سید حسین علی رضوی کے بھائی (بمطابق شجرہ)۔', 'shajra', '{}', 38)
on conflict (id) do update set
  name = case when public.people.name = '' then excluded.name else public.people.name end,
  name_ur = case when public.people.name_ur = '' then excluded.name_ur else public.people.name_ur end,
  birth = case when public.people.birth = '' then excluded.birth else public.people.birth end,
  birth_ur = case when public.people.birth_ur = '' then excluded.birth_ur else public.people.birth_ur end,
  death = case when public.people.death = '' then excluded.death else public.people.death end,
  death_ur = case when public.people.death_ur = '' then excluded.death_ur else public.people.death_ur end,
  birthplace = case when public.people.birthplace = '' then excluded.birthplace else public.people.birthplace end,
  birthplace_ur = case when public.people.birthplace_ur = '' then excluded.birthplace_ur else public.people.birthplace_ur end,
  residence = case when public.people.residence = '' then excluded.residence else public.people.residence end,
  residence_ur = case when public.people.residence_ur = '' then excluded.residence_ur else public.people.residence_ur end,
  spouse = case when public.people.spouse = '' then excluded.spouse else public.people.spouse end,
  spouse_ur = case when public.people.spouse_ur = '' then excluded.spouse_ur else public.people.spouse_ur end,
  notes = case when public.people.notes = '' then excluded.notes else public.people.notes end,
  notes_ur = case when public.people.notes_ur = '' then excluded.notes_ur else public.people.notes_ur end;
