/* Copy the live tree out of Supabase and into a plain file in the repo.
 *
 * This is the twenty-year insurance policy. It does four jobs at once:
 *
 *   1. Keeps the offline fallback current. store.js already falls back to the
 *      bundled data when Supabase is unreachable, so the tree stays readable
 *      even if the database is paused, deleted, or the company is gone. That
 *      fallback is only worth having if it is recent.
 *   2. Prevents the free-plan pause. Supabase pauses projects after 7 days of
 *      low activity; a weekly read counts as activity.
 *   3. Creates a permanent, versioned backup. Every run commits, so git holds
 *      the full history of the record — no backup files to manage or lose.
 *   4. Needs no credentials. It reads with the public anon key that is already
 *      in assets/config.js, because `people` is world-readable by design. So
 *      there is no secret to expire, rotate, or forget.
 *
 * Run: node tools/snapshot.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const CONFIG = path.join(ROOT, 'assets', 'config.js');
const OUT = path.join(ROOT, 'assets', 'snapshot.js');

function readConfig() {
  const src = fs.readFileSync(CONFIG, 'utf8');
  const url = (src.match(/SUPABASE_URL:\s*'([^']*)'/) || [])[1];
  const key = (src.match(/SUPABASE_ANON_KEY:\s*'([^']*)'/) || [])[1];
  if (!url || !key) throw new Error('SUPABASE_URL / SUPABASE_ANON_KEY not set in assets/config.js');
  return { url, key };
}

async function main() {
  const { url, key } = readConfig();

  const res = await fetch(`${url}/rest/v1/people?select=*&order=sort_order.asc`, {
    headers: { apikey: key, Authorization: `Bearer ${key}` }
  });
  if (!res.ok) throw new Error(`Supabase returned ${res.status} ${res.statusText}`);

  const people = await res.json();

  // Refuse to overwrite a good snapshot with a bad read. An empty or tiny
  // result almost certainly means a broken query or a wiped table, and
  // committing that would destroy the very fallback this exists to protect.
  if (!Array.isArray(people) || people.length === 0) {
    throw new Error('Refusing to write: the database returned no people.');
  }
  if (fs.existsSync(OUT)) {
    const prev = (fs.readFileSync(OUT, 'utf8').match(/"id":/g) || []).length;
    if (prev && people.length < prev * 0.5) {
      throw new Error(
        `Refusing to write: people dropped from ~${prev} to ${people.length}. ` +
        'If this shrink is intentional, delete assets/snapshot.js and re-run.');
    }
  }

  const body =
`/* GENERATED by tools/snapshot.js — do not edit by hand.
 *
 * A copy of the live tree, taken ${new Date().toISOString().slice(0, 10)}.
 * Loaded after data.js and replaces the seed, so the site shows the family's
 * current record even with no database available. Delete this file and the
 * site falls back to the original transcription in data.js.
 */
window.SEED_PEOPLE = ${JSON.stringify(people, null, 2)};
window.SNAPSHOT_TAKEN = ${JSON.stringify(new Date().toISOString())};
`;

  const before = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  // Ignore the date line when deciding whether anything really changed, so a
  // quiet week does not produce a pointless commit.
  const strip = s => s.replace(/taken \d{4}-\d{2}-\d{2}/, '').replace(/SNAPSHOT_TAKEN = "[^"]*"/, '');

  if (strip(before) === strip(body)) {
    console.log(`No change — ${people.length} people, snapshot already current.`);
    process.exit(0);
  }

  fs.writeFileSync(OUT, body, 'utf8');
  console.log(`Wrote ${OUT} — ${people.length} people.`);
}

main().catch(err => { console.error(err.message); process.exit(1); });
